[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
blind_auction = "Cy9dGwHUyKeSqfe4GUvwXB5V9zbzo3mk2tB6Jzgiu3q7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/junyang/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
